// `CreationTimestamp` package name
package org.zouarioss.skinnedratorm.annotations;

// `java` import(s)
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a field to be automatically populated with the entity creation
 * timestamp.
 *
 * <p>
 * The {@code @CreationTimestamp} annotation indicates that the annotated
 * field should be automatically assigned the current timestamp value when
 * the entity is first persisted. This value is typically generated by the
 * ORM framework at insert time and is not meant to be manually updated.
 * </p>
 *
 * <p>
 * This annotation is retained at runtime, allowing the ORM engine to
 * detect it via reflection and inject the appropriate timestamp value
 * during the entity lifecycle.
 * </p>
 *
 * <h2>Supported Field Types:</h2>
 * <ul>
 * <li>{@code java.time.LocalDateTime}</li>
 * <li>{@code java.time.Instant}</li>
 * <li>{@code java.util.Date}</li>
 * <li>{@code long}</li>
 * </ul>
 *
 * <h2>Usage Example:</h2>
 *
 * <pre>{@code
 * @CreationTimestamp
 * private LocalDateTime createdAt;
 * }</pre>
 *
 * <p>
 * The value is set only once during the initial persistence operation
 * and is typically non-updatable.
 * </p>
 *
 * @author ZouariOmar (zouariomar20@gmail.com)
 * @version 1.0
 * @since 2026-02-15
 *
 * @see org.zouarioss.skinnedratorm.annotations.UpdateTimestamp
 *
 *      <a href=
 *      "https://github.com/zouari-oss/skinned-rat-orm/tree/main/project/lib/src/main/java/org/zouarioss/skinnedratorm/annotations/CreationTimestamp.java">
 *      CreationTimestamp.java
 *      </a>
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface CreationTimestamp {
} // CreationTimestamp @interface
