/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `maven-publish`
    signing
}

group = "org.zouarioss"
version = "1.0.2"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // MariaDB JDBC driver for testing
    testImplementation("org.mariadb.jdbc:mariadb-java-client:3.3.2")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    withJavadocJar()
    withSourcesJar()
    tasks.withType<Javadoc>().configureEach {
    (options as? StandardJavadocDocletOptions)?.apply {
        addBooleanOption("author", true)
        addBooleanOption("version", true)

        encoding = "UTF-8"
        windowTitle = "Skinned Rat ORM 1.0.2 API"
        docTitle = "Skinned Rat ORM API Documentation"
    }
  }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform {
        // Exclude integration tests by default
        excludeTags("integration")
    }
}

// Add task for integration tests
tasks.register<Test>("integrationTest") {
    description = "Runs integration tests"
    group = "verification"

    testClassesDirs = sourceSets["test"].output.classesDirs
    classpath = sourceSets["test"].runtimeClasspath
 
    useJUnitPlatform {
        includeTags("integration")
    }

    shouldRunAfter(tasks.test)
}

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            from(components["java"])

            groupId = "org.zouarioss"
            artifactId = "skinnedratorm"
            version = "1.0.2"
 
           pom {
                name.set("Skinned Rat ORM")
                description.set("A lightweight ORM framework for Java with annotation-based entity mapping")
                url.set("https://github.com/zouari-oss/skinned-rat-orm")

                licenses {
                    license {
                        name.set("GPL-3.0 License")
                        url.set("https://opensource.org/license/GPL-3.0")
                    }
                }

                developers {
                    developer {
                        id.set("zouariomar")
                        name.set("ZouariOmar")
                        email.set("zouariomar20@gmail.com")
                    }
                }
 
                scm {
                    connection.set("scm:git:git://github.com/zouari-oss/skinned-rat-orm.git")
                    developerConnection.set("scm:git:ssh://github.com/zouari-oss/skinned-rat-orm.git")
                    url.set("https://github.com/zouari-oss/skinned-rat-orm")
                }
            }
        }
    }

    repositories {
        // Local Maven repository (for testing)
        maven {
            name = "local"
            url = layout.buildDirectory.dir("repo").map { it.asFile.toURI() }.get()
        }

        // GitHub Packages
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/zouari-oss/skinned-rat-orm")
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}

signing {
    // Only sign if publishing to Maven Central
    setRequired { gradle.taskGraph.hasTask("publishMavenJavaPublicationToOSSRHRepository") }
    sign(publishing.publications["mavenJava"])
}
